javascript_compressor: closure
gzip_assets:           off

s3_bucket:             <%= ENV['S3_ASSET_BUCKET'] %>
s3_access_key_id:      <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret_access_key:  <%= ENV['S3_SECRET_ACCESS_KEY'] %>

javascripts:
  viso:
    - public/javascripts/vendor/jquery-1.6.1.min.js
    - public/javascripts/vendor/modernizr-1.7.min.js
    - public/javascripts/image.js
    - public/javascripts/other.js

stylesheets:
  viso:
    - public/stylesheets/reset.css
    - public/stylesheets/monsoon.css
    - public/stylesheets/image.css
    - public/stylesheets/other.css
    - public/stylesheets/text.css
    - public/stylesheets/syntax.css
